oldXMenu: add missing #include <string.h>
Some of the files in oldXMenu use functions from string.h without
including that header which results in compile warnings:

	ChgPane.c:46:5: warning: implicit declaration of function ‘strlen’
	ChgPane.c:46:20: warning: incompatible implicit declaration of
		built-in function ‘strlen’
	ChgSel.c:62:2: warning: implicit declaration of function ‘strlen’
	ChgSel.c:62:17: warning: incompatible implicit declaration of built-in
		function ‘strlen’
	Create.c:220:5: warning: implicit declaration of function ‘strcmp’
	InsPane.c:65:5: warning: implicit declaration of function ‘strlen’
	InsPane.c:65:20: warning: incompatible implicit declaration of
		built-in function ‘strlen’
	InsSel.c:68:5: warning: implicit declaration of function ‘strlen’
	InsSel.c:68:20: warning: incompatible implicit declaration of built-in
		function ‘strlen’
	InsSel.c:75:5: warning: implicit declaration of function ‘strcmp’

Add the necessary ‘#include <string.h>’.

oldXMenu/ChgPane.c, oldXMenu/ChgSel.c, oldXMenu/Create.c, oldXMenu/InsPane.c,
oldXMenu/InsSel.c: add missing #include <string.h>